# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
#container: "docker://continuumio/miniconda3"

#workdir: "/cluster/projects/mcgahalab/data/mcgahalab/sacher_nsclc_tslp/snakemake-workflow/"
#workdir: "/cluster/projects/mcgahalab/data/mcgahalab/teresa/210121_A00827_0252_BH25WGDRXY_McGaha_Kebria/snakemake-workflow/"
#workdir: "/cluster/projects/mcgahalab/data/mcgahalab/sara_MSM_SSM"
#workdir: "/cluster/projects/mcgahalab/data/mcgahalab/INSPIRE"
workdir: "/cluster/projects/mcgahalab/data/mcgahalab/wither_mcgaha_ram/snakemake_workflow/"
#workdir: "/cluster/home/quever/workflows/initialize/rnaseq_test/"

##### load rules #####
include: "rules/common.smk"
include: "rules/ref.smk"
include: "rules/trim.smk"
include: "rules/qc.smk"
include: "rules/align.smk"
include: "rules/diffexp.smk"
include: "rules/countmatrix.smk"
include: "rules/immune.smk"
include: "rules/genotyping.smk"


##### target rules #####


rule all:
    input:
        "results/pca.pdf",
        get_final_output(),
        "results/immune/immunedeconv.rds",
        "results/counts/all_tpm.tsv",
        "results/qc/multiqc_report.html",
